export const dummyBooks = [
  {
    _id: "1",
    name: "Foundations of Science",
    image: "/images/books/book_1.png",
    offerPrice: 15,
    description: "Learn energy, motion, and forces with simple examples and visuals for young science explorers.",
    category: "Academic",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "2",
    name: "Everyday Math Explained",
    image: "/images/books/book_2.png",
    offerPrice: 20,
    description: "Basic math for daily life: budgeting, measuring, percentages, and more made easy and clear.",
    category: "Academic",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "3",
    name: "Basics of Chemistry",
    image: "/images/books/book_3.png",
    offerPrice: 10,
    description: "Explore atoms, matter, and reactions in simple steps with visuals and easy chemistry terms.",
    category: "Academic",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "4",
    name: "Tech and Logic Essentials",
    image: "/images/books/book_4.png",
    offerPrice: 25,
    description: "Learn coding basics, algorithms, and problem-solving using fun tasks and clear explanations.",
    category: "Academic",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "5",
    name: "World Events and Ideas",
    image: "/images/books/book_5.png",
    offerPrice: 15,
    description: "Discover key global events, wars, and changes in a short, simple guide to world history.",
    category: "Academic",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "6",
    name: "Understanding Life Science",
    image: "/images/books/book_6.png",
    offerPrice: 18,
    description: "Explore cells, genetics, ecosystems, and biology basics in easy terms for curious readers.",
    category: "Academic",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "7",
    name: "The Magic Treehouse",
    image: "/images/books/book_7.png",
    offerPrice: 12,
    description: "Time travel tales with fun lessons, magic, and learning for young adventurous minds.",
    category: "Children",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "8",
    name: "Animal Friends Forever",
    image: "/images/books/book_8.png",
    offerPrice: 14,
    description: "Stories of animal friendships, teamwork, and kindness told with colorful illustrations.",
    category: "Children",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "9",
    name: "Fairyland Dreams",
    image: "/images/books/book_9.png",
    offerPrice: 18,
    description: "A magical land of fairies and princesses solving problems with courage and teamwork.",
    category: "Children",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "10",
    name: "Super Jack and the Dragon",
    image: "/images/books/book_10.png",
    offerPrice: 20,
    description: "Join Jack in his brave journey to defeat a dragon and save his town.",
    category: "Children",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "11",
    name: "Treasure Island Map",
    image: "/images/books/book_11.png",
    offerPrice: 15,
    description: "A thrilling quest with hidden maps, clues, and a treasure adventure to enjoy.",
    category: "Children",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "12",
    name: "Kids in Space",
    image: "/images/books/book_12.png",
    offerPrice: 17,
    description: "Explore planets, rockets, and space fun with children on a wild ride to the stars.",
    category: "Children",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "13",
    name: "Healthy Living Guide",
    image: "/images/books/book_13.png",
    offerPrice: 20,
    description: "Simple tips on staying fit, eating right, and living a healthier life with balance and wellness.",
    category: "Health",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "14",
    name: "Yoga and You",
    image: "/images/books/book_14.png",
    offerPrice: 18,
    description: "Basic yoga poses and routines to improve flexibility, calm the mind, and reduce daily stress.",
    category: "Health",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "15",
    name: "Nutrition Simplified",
    image: "/images/books/book_15.png",
    offerPrice: 15,
    description: "Learn about healthy eating, food groups, and smart choices to boost energy and stay strong.",
    category: "Health",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "16",
    name: "Rest and Recharge",
    image: "/images/books/book_16.png",
    offerPrice: 22,
    description: "Discover how sleep, rest, and relaxation improve mood, health, and focus in daily life.",
    category: "Health",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "17",
    name: "Quick Fitness Plan",
    image: "/images/books/book_17.png",
    offerPrice: 25,
    description: "A short workout routine to keep fit, gain energy, and build healthy habits for every day.",
    category: "Health",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "18",
    name: "Nature Heals",
    image: "/images/books/book_18.png",
    offerPrice: 18,
    description: "Discover how spending time in nature helps reduce stress, clear your mind, and feel refreshed.",
    category: "Health",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "19",
    name: "Whispers in the Dark",
    image: "/images/books/book_19.png",
    offerPrice: 30,
    description: "A creepy tale of shadows and voices that haunt a house deep within a forgotten forest.",
    category: "Horror",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "20",
    name: "The Haunted Woods",
    image: "/images/books/book_20.png",
    offerPrice: 25,
    description: "Mysterious events unfold in a forest where no one returns once they enter after sunset.",
    category: "Horror",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "21",
    name: "Voices from the Grave",
    image: "/images/books/book_21.png",
    offerPrice: 18,
    description: "Eerie whispers call from the cemetery, revealing long-lost secrets buried deep beneath the ground.",
    category: "Horror",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "22",
    name: "Night of the Shadows",
    image: "/images/books/book_22.png",
    offerPrice: 22,
    description: "When night falls, evil rises. A town is stalked by dark figures and fearsome creatures unknown.",
    category: "Horror",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "23",
    name: "The Mirror's Curse",
    image: "/images/books/book_23.png",
    offerPrice: 28,
    description: "A haunted mirror shows twisted realities, drawing people in and trapping them forever inside it.",
    category: "Horror",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "24",
    name: "Basement of Bones",
    image: "/images/books/book_24.png",
    offerPrice: 30,
    description: "Dark secrets lurk beneath an old home, where bones whisper and spirits walk in silence.",
    category: "Horror",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "25",
    name: "Start Your Own Business",
    image: "/images/books/book_25.png",
    offerPrice: 22,
    description: "Step-by-step guide to launching a business from idea to reality, even with little experience.",
    category: "Business",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "26",
    name: "Brand Like a Pro",
    image: "/images/books/book_26.png",
    offerPrice: 24,
    description: "Master the art of branding, learn customer psychology, and build a strong, lasting identity.",
    category: "Business",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "27",
    name: "Lead with Purpose",
    image: "/images/books/book_27.png",
    offerPrice: 26,
    description: "Gain leadership skills to inspire, manage, and grow your business or team with confidence.",
    category: "Business",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "28",
    name: "Finance for Everyone",
    image: "/images/books/book_28.png",
    offerPrice: 18,
    description: "Easy ways to manage money, save smartly, and understand your personal and business finances.",
    category: "Business",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "29",
    name: "Mastering Negotiation",
    image: "/images/books/book_29.png",
    offerPrice: 22,
    description: "Practical techniques to win deals, communicate clearly, and negotiate in any business setting.",
    category: "Business",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "30",
    name: "Productivity Hacks",
    image: "/images/books/book_30.png",
    offerPrice: 20,
    description: "Time-saving strategies to stay organized, finish tasks faster, and make every day productive.",
    category: "Business",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "31",
    name: "Ancient Civilizations",
    image: "/images/books/book_31.png",
    offerPrice: 15,
    description: "Explore early human societies, how they lived, built cities, and shaped the world today.",
    category: "History",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "32",
    name: "World War Chronicles",
    image: "/images/books/book_32.png",
    offerPrice: 18,
    description: "Learn about major battles, leaders, and events from both world wars that shaped nations.",
    category: "History",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "33",
    name: "Leaders Who Changed the World",
    image: "/images/books/book_33.png",
    offerPrice: 12,
    description: "Discover inspiring stories of historical leaders who transformed countries and inspired generations.",
    category: "History",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "34",
    name: "The Rise and Fall of Empires",
    image: "/images/books/book_34.png",
    offerPrice: 20,
    description: "From Rome to the Ottomans, explore how empires grew powerful and what led to collapse.",
    category: "History",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "35",
    name: "History of Inventions",
    image: "/images/books/book_35.png",
    offerPrice: 22,
    description: "A journey through game-changing inventions that shaped modern life and changed human progress.",
    category: "History",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "36",
    name: "Explorers and Voyages",
    image: "/images/books/book_36.png",
    offerPrice: 25,
    description: "Tales of famous explorers, their discoveries, and how they mapped the unknown world.",
    category: "History",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "37",
    name: "Into the Unknown",
    image: "/images/books/book_37.png",
    offerPrice: 16,
    description: "Follow a bold journey through mysterious lands filled with danger, courage, and discovery.",
    category: "Adventure",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "38",
    name: "Lost in the Jungle",
    image: "/images/books/book_38.png",
    offerPrice: 19,
    description: "Lost in the Jungle",
    category: "Adventure",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "39",
    name: "Mountains of Mystery",
    image: "/images/books/book_39.png",
    offerPrice: 20,
    description: "Scaling icy peaks and ancient caves, a group finds danger and secrets buried in snow.",
    category: "Adventure",
    date: 1716634345448,
    popular: true,
    inStock: true,
  },
  {
    _id: "40",
    name: "The Desert Odyssey",
    image: "/images/books/book_40.png",
    offerPrice: 23,
    description: "An epic quest across blazing sands, where courage and wit are the only means to survive.",
    category: "Adventure",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "41",
    name: "Caves of Wonder",
    image: "/images/books/book_41.png",
    offerPrice: 22,
    description: "Deep underground, a hidden world awaits with lost treasures, strange creatures, and ancient magic.",
    category: "Adventure",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
  {
    _id: "42",
    name: "Frozen Expedition",
    image: "/images/books/book_42.png",
    offerPrice: 21,
    description: "Brave the icy tundra and uncover secrets buried beneath snow and time in this tale.",
    category: "Adventure",
    date: 1716634345448,
    popular: false,
    inStock: true,
  },
];
