import type { Book } from "@/types";

export const dummyBooks: Book[] = [
  {
    _id: "1",
    title: "Foundations of Science",
    cover_image: "/images/books/book_1.png",
    author: { name: "Unknown Author" },
    category: { name: "Academic" },
    summary: "Learn energy, motion, and forces with simple examples and visuals for young science explorers.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 15,000",
      total_pages: "150 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Academic", "Science"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Foundations+of+Science" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "2",
    title: "Everyday Math Explained",
    cover_image: "/images/books/book_2.png",
    author: { name: "Unknown Author" },
    category: { name: "Academic" },
    summary: "Basic math for daily life: budgeting, measuring, percentages, and more made easy and clear.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 20,000",
      total_pages: "200 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Academic", "Math"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Everyday+Math+Explained" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "3",
    title: "Basics of Chemistry",
    cover_image: "/images/books/book_3.png",
    author: { name: "Unknown Author" },
    category: { name: "Academic" },
    summary: "Explore atoms, matter, and reactions in simple steps with visuals and easy chemistry terms.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 10,000",
      total_pages: "180 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Academic", "Chemistry"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Basics+of+Chemistry" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "4",
    title: "Tech and Logic Essentials",
    cover_image: "/images/books/book_4.png",
    author: { name: "Unknown Author" },
    category: { name: "Academic" },
    summary: "Learn coding basics, algorithms, and problem-solving using fun tasks and clear explanations.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 25,000",
      total_pages: "220 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Academic", "Technology"],
    buy_links: [
      { store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Tech+and+Logic+Essentials" },
    ],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "5",
    title: "World Events and Ideas",
    cover_image: "/images/books/book_5.png",
    author: { name: "Unknown Author" },
    category: { name: "Academic" },
    summary: "Discover key global events, wars, and changes in a short, simple guide to world history.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 15,000",
      total_pages: "250 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Academic", "History"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=World+Events+and+Ideas" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "6",
    title: "Understanding Life Science",
    cover_image: "/images/books/book_6.png",
    author: { name: "Unknown Author" },
    category: { name: "Academic" },
    summary: "Explore cells, genetics, ecosystems, and biology basics in easy terms for curious readers.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "190 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Academic", "Biology"],
    buy_links: [
      { store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Understanding+Life+Science" },
    ],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "7",
    title: "The Magic Treehouse",
    cover_image: "/images/books/book_7.png",
    author: { name: "Unknown Author" },
    category: { name: "Children" },
    summary: "Time travel tales with fun lessons, magic, and learning for young adventurous minds.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 12,000",
      total_pages: "100 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Children", "Adventure"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=The+Magic+Treehouse" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "8",
    title: "Animal Friends Forever",
    cover_image: "/images/books/book_8.png",
    author: { name: "Unknown Author" },
    category: { name: "Children" },
    summary: "Stories of animal friendships, teamwork, and kindness told with colorful illustrations.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 14,000",
      total_pages: "80 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Children", "Animals"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Animal+Friends+Forever" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "9",
    title: "Fairyland Dreams",
    cover_image: "/images/books/book_9.png",
    author: { name: "Unknown Author" },
    category: { name: "Children" },
    summary: "A magical land of fairies and princesses solving problems with courage and teamwork.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "120 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Children", "Fantasy"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Fairyland+Dreams" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "10",
    title: "Super Jack and the Dragon",
    cover_image: "/images/books/book_10.png",
    author: { name: "Unknown Author" },
    category: { name: "Children" },
    summary: "Join Jack in his brave journey to defeat a dragon and save his town.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 20,000",
      total_pages: "90 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Children", "Action"],
    buy_links: [
      { store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Super+Jack+and+the+Dragon" },
    ],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "11",
    title: "Treasure Island Map",
    cover_image: "/images/books/book_11.png",
    author: { name: "Unknown Author" },
    category: { name: "Children" },
    summary: "A thrilling quest with hidden maps, clues, and a treasure adventure to enjoy.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 15,000",
      total_pages: "110 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Children", "Adventure"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Treasure+Island+Map" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "12",
    title: "Kids in Space",
    cover_image: "/images/books/book_12.png",
    author: { name: "Unknown Author" },
    category: { name: "Children" },
    summary: "Explore planets, rockets, and space fun with children on a wild ride to the stars.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 17,000",
      total_pages: "130 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Children", "Space"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Kids+in+Space" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "13",
    title: "Healthy Living Guide",
    cover_image: "/images/books/book_13.png",
    author: { name: "Unknown Author" },
    category: { name: "Health" },
    summary: "Simple tips on staying fit, eating right, and living a healthier life with balance and wellness.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 20,000",
      total_pages: "160 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Health", "Wellness"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Healthy+Living+Guide" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "14",
    title: "Yoga and You",
    cover_image: "/images/books/book_14.png",
    author: { name: "Unknown Author" },
    category: { name: "Health" },
    summary: "Basic yoga poses and routines to improve flexibility, calm the mind, and reduce daily stress.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "140 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Health", "Yoga"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Yoga+and+You" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "15",
    title: "Nutrition Simplified",
    cover_image: "/images/books/book_15.png",
    author: { name: "Unknown Author" },
    category: { name: "Health" },
    summary: "Learn about healthy eating, food groups, and smart choices to boost energy and stay strong.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 15,000",
      total_pages: "170 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Health", "Nutrition"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Nutrition+Simplified" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "16",
    title: "Rest and Recharge",
    cover_image: "/images/books/book_16.png",
    author: { name: "Unknown Author" },
    category: { name: "Health" },
    summary: "Discover how sleep, rest, and relaxation improve mood, health, and focus in daily life.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 22,000",
      total_pages: "155 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Health", "Self-Care"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Rest+and+Recharge" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "17",
    title: "Quick Fitness Plan",
    cover_image: "/images/books/book_17.png",
    author: { name: "Unknown Author" },
    category: { name: "Health" },
    summary: "A short workout routine to keep fit, gain energy, and build healthy habits for every day.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 25,000",
      total_pages: "130 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Health", "Fitness"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Quick+Fitness+Plan" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "18",
    title: "Nature Heals",
    cover_image: "/images/books/book_18.png",
    author: { name: "Unknown Author" },
    category: { name: "Health" },
    summary: "Discover how spending time in nature helps reduce stress, clear your mind, and feel refreshed.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "165 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Health", "Nature"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Nature+Heals" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "19",
    title: "Whispers in the Dark",
    cover_image: "/images/books/book_19.png",
    author: { name: "Unknown Author" },
    category: { name: "Horror" },
    summary: "A creepy tale of shadows and voices that haunt a house deep within a forgotten forest.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 30,000",
      total_pages: "320 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Horror", "Ghost"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Whispers+in+the+Dark" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "20",
    title: "The Haunted Woods",
    cover_image: "/images/books/book_20.png",
    author: { name: "Unknown Author" },
    category: { name: "Horror" },
    summary: "Mysterious events unfold in a forest where no one returns once they enter after sunset.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 25,000",
      total_pages: "290 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Horror", "Mystery"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=The+Haunted+Woods" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "21",
    title: "Voices from the Grave",
    cover_image: "/images/books/book_21.png",
    author: { name: "Unknown Author" },
    category: { name: "Horror" },
    summary: "Eerie whispers call from the cemetery, revealing long-lost secrets buried deep beneath the ground.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "270 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Horror", "Secrets"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Voices+from+the+Grave" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "22",
    title: "Night of the Shadows",
    cover_image: "/images/books/book_22.png",
    author: { name: "Unknown Author" },
    category: { name: "Horror" },
    summary: "When night falls, evil rises. A town is stalked by dark figures and fearsome creatures unknown.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 22,000",
      total_pages: "310 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Horror", "Creatures"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Night+of+the+Shadows" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "23",
    title: "The Mirror's Curse",
    cover_image: "/images/books/book_23.png",
    author: { name: "Unknown Author" },
    category: { name: "Horror" },
    summary: "A haunted mirror shows twisted realities, drawing people in and trapping them forever inside it.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 28,000",
      total_pages: "285 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Horror", "Supernatural"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=The+Mirror's+Curse" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "24",
    title: "Basement of Bones",
    cover_image: "/images/books/book_24.png",
    author: { name: "Unknown Author" },
    category: { name: "Horror" },
    summary: "Dark secrets lurk beneath an old home, where bones whisper and spirits walk in silence.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 30,000",
      total_pages: "340 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Horror", "Thriller"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Basement+of+Bones" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "25",
    title: "Start Your Own Business",
    cover_image: "/images/books/book_25.png",
    author: { name: "Unknown Author" },
    category: { name: "Business" },
    summary: "Step-by-step guide to launching a business from idea to reality, even with little experience.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 22,000",
      total_pages: "230 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Business", "Startup"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Start+Your+Own+Business" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "26",
    title: "Brand Like a Pro",
    cover_image: "/images/books/book_26.png",
    author: { name: "Unknown Author" },
    category: { name: "Business" },
    summary: "Master the art of branding, learn customer psychology, and build a strong, lasting identity.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 24,000",
      total_pages: "215 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Business", "Branding"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Brand+Like+a+Pro" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "27",
    title: "Lead with Purpose",
    cover_image: "/images/books/book_27.png",
    author: { name: "Unknown Author" },
    category: { name: "Business" },
    summary: "Gain leadership skills to inspire, manage, and grow your business or team with confidence.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 26,000",
      total_pages: "250 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Business", "Leadership"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Lead+with+Purpose" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "28",
    title: "Finance for Everyone",
    cover_image: "/images/books/book_28.png",
    author: { name: "Unknown Author" },
    category: { name: "Business" },
    summary: "Easy ways to manage money, save smartly, and understand your personal and business finances.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "200 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Business", "Finance"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Finance+for+Everyone" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "29",
    title: "Mastering Negotiation",
    cover_image: "/images/books/book_29.png",
    author: { name: "Unknown Author" },
    category: { name: "Business" },
    summary: "Practical techniques to win deals, communicate clearly, and negotiate in any business setting.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 22,000",
      total_pages: "190 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Business", "Negotiation"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Mastering+Negotiation" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "30",
    title: "Productivity Hacks",
    cover_image: "/images/books/book_30.png",
    author: { name: "Unknown Author" },
    category: { name: "Business" },
    summary: "Time-saving strategies to stay organized, finish tasks faster, and make every day productive.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 20,000",
      total_pages: "180 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Business", "Productivity"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Productivity+Hacks" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "31",
    title: "Ancient Civilizations",
    cover_image: "/images/books/book_31.png",
    author: { name: "Unknown Author" },
    category: { name: "History" },
    summary: "Explore early human societies, how they lived, built cities, and shaped the world today.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 15,000",
      total_pages: "280 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["History", "Civilization"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Ancient+Civilizations" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "32",
    title: "World War Chronicles",
    cover_image: "/images/books/book_32.png",
    author: { name: "Unknown Author" },
    category: { name: "History" },
    summary: "Learn about major battles, leaders, and events from both world wars that shaped nations.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 18,000",
      total_pages: "350 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["History", "War"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=World+War+Chronicles" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "33",
    title: "Leaders Who Changed the World",
    cover_image: "/images/books/book_33.png",
    author: { name: "Unknown Author" },
    category: { name: "History" },
    summary: "Discover inspiring stories of historical leaders who transformed countries and inspired generations.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 12,000",
      total_pages: "260 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["History", "Biography"],
    buy_links: [
      { store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Leaders+Who+Changed+the+World" },
    ],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "34",
    title: "The Rise and Fall of Empires",
    cover_image: "/images/books/book_34.png",
    author: { name: "Unknown Author" },
    category: { name: "History" },
    summary: "From Rome to the Ottomans, explore how empires grew powerful and what led to collapse.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 20,000",
      total_pages: "320 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["History", "Empires"],
    buy_links: [
      { store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=The+Rise+and+Fall+of+Empires" },
    ],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "35",
    title: "History of Inventions",
    cover_image: "/images/books/book_35.png",
    author: { name: "Unknown Author" },
    category: { name: "History" },
    summary: "A journey through game-changing inventions that shaped modern life and changed human progress.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 22,000",
      total_pages: "240 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["History", "Inventions"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=History+of+Inventions" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "36",
    title: "Explorers and Voyages",
    cover_image: "/images/books/book_36.png",
    author: { name: "Unknown Author" },
    category: { name: "History" },
    summary: "Tales of famous explorers, their discoveries, and how they mapped the unknown world.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 25,000",
      total_pages: "275 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["History", "Exploration"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Explorers+and+Voyages" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "37",
    title: "Into the Unknown",
    cover_image: "/images/books/book_37.png",
    author: { name: "Unknown Author" },
    category: { name: "Adventure" },
    summary: "Follow a bold journey through mysterious lands filled with danger, courage, and discovery.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 16,000",
      total_pages: "300 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Adventure", "Mystery"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Into+the+Unknown" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "38",
    title: "Lost in the Jungle",
    cover_image: "/images/books/book_38.png",
    author: { name: "Unknown Author" },
    category: { name: "Adventure" },
    summary: "Lost in the Jungle",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 19,000",
      total_pages: "280 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Adventure", "Jungle"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Lost+in+the+Jungle" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "39",
    title: "Mountains of Mystery",
    cover_image: "/images/books/book_39.png",
    author: { name: "Unknown Author" },
    category: { name: "Adventure" },
    summary: "Scaling icy peaks and ancient caves, a group finds danger and secrets buried in snow.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 20,000",
      total_pages: "310 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Adventure", "Survival"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Mountains+of+Mystery" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "40",
    title: "The Desert Odyssey",
    cover_image: "/images/books/book_40.png",
    author: { name: "Unknown Author" },
    category: { name: "Adventure" },
    summary: "An epic quest across blazing sands, where courage and wit are the only means to survive.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 23,000",
      total_pages: "330 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Adventure", "Desert"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=The+Desert+Odyssey" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "41",
    title: "Caves of Wonder",
    cover_image: "/images/books/book_41.png",
    author: { name: "Unknown Author" },
    category: { name: "Adventure" },
    summary: "Deep underground, a hidden world awaits with lost treasures, strange creatures, and ancient magic.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 22,000",
      total_pages: "295 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Adventure", "Magic"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Caves+of+Wonder" }],
    publisher: "Gramedia Pustaka Utama",
  },
  {
    _id: "42",
    title: "Frozen Expedition",
    cover_image: "/images/books/book_42.png",
    author: { name: "Unknown Author" },
    category: { name: "Adventure" },
    summary: "Brave the icy tundra and uncover secrets buried beneath snow and time in this tale.",
    details: {
      no_gm: "0",
      isbn: "0",
      price: "Rp 21,000",
      total_pages: "285 pages",
      size: "13.5 x 20 cm",
      published_date: "2024-05-25",
      format: "Soft Cover",
    },
    tags: ["Adventure", "Exploration"],
    buy_links: [{ store: "Search on Gramedia.com", url: "https://www.gramedia.com/search?q=Frozen+Expedition" }],
    publisher: "Gramedia Pustaka Utama",
  },
];
